# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Douban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('rate', models.FloatField()),
                ('url', models.CharField(max_length=128)),
                ('cover', models.CharField(max_length=255)),
                ('director', models.TextField()),
                ('scriptwriter', models.TextField()),
                ('protagonist', models.TextField()),
                ('m_type', models.CharField(max_length=128)),
                ('region', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('release_time', models.TextField()),
                ('numbers', models.CharField(max_length=30)),
                ('run_time', models.CharField(max_length=128)),
                ('other_title', models.CharField(max_length=255)),
                ('imdb_link', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=128)),
                ('comment_num', models.IntegerField()),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name_plural': '豆瓣',
                'managed': False,
                'db_table': 'douban',
            },
        ),
    ]
